"""adding avatar to user

Revision ID: 3591007d0dca
Revises: 
Create Date: 2025-05-11 17:04:59.018958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3591007d0dca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar "
        "VARCHAR(120) DEFAULT 'default.jpg' NOT NULL"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS avatar")

    # ### end Alembic commands ###
